namespace BigBoss.Core.Entities;

public class Live
{
    public Guid Id { get; set; }

    // Info
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public LiveType Type { get; set; }

    // Scheduling
    public DateTime ScheduledAt { get; set; }
    public DateTime? StartedAt { get; set; }
    public DateTime? EndedAt { get; set; }

    // Streaming
    public string? StreamUrl { get; set; }
    public string? ReplayUrl { get; set; }
    public string? ThumbnailUrl { get; set; }

    // Chapters (generated by AI post-live)
    public string? ChaptersJson { get; set; }

    // Stats
    public int PeakViewers { get; set; }
    public int TotalViews { get; set; }
    public int TotalLikes { get; set; }
    public int TotalComments { get; set; }

    // Associated session (for workout lives)
    public Guid? GeneratedSessionId { get; set; }

    // Timestamps
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;
}

public enum LiveType
{
    Workout = 1,
    Nutrition = 2,
    QnA = 3,
    ChallengeResults = 4,
    Masterclass = 5
}
