// <auto-generated />
using System;
using System.Collections.Generic;
using BigBoss.Core.Enums;
using BigBoss.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BigBoss.Infrastructure.Migrations
{
    [DbContext(typeof(BigBossDbContext))]
    [Migration("20260328134223_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BigBoss.Core.Entities.BodyStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BodyFatPercent")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ChestCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("HipsCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LeftArmCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LeftCalfCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("LeftThighCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("NeckCm")
                        .HasColumnType("numeric");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("RightArmCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RightCalfCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RightThighCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ShouldersCm")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WaistCm")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BodyStats");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Challenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetricUnit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RewardDescription")
                        .HasColumnType("text");

                    b.Property<string>("RewardImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Challenges");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.CoachMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("ModelUsed")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TokensUsed")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("CoachMessages");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Exercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<List<Guid>>("AlternativeExerciseIds")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("alternative_exercise_ids");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<List<string>>("CoachingCues")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("coaching_cues");

                    b.Property<List<string>>("CommonMistakes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("common_mistakes");

                    b.Property<int>("ComplexityScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("complexity_score");

                    b.Property<List<string>>("Contraindications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contraindications");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.Property<string>("GifPreviewUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("gif_preview_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int>("MaxRepsEndurance")
                        .HasColumnType("integer")
                        .HasColumnName("max_reps_endurance");

                    b.Property<int>("MaxRepsHypertrophy")
                        .HasColumnType("integer")
                        .HasColumnName("max_reps_hypertrophy");

                    b.Property<int>("MaxRepsStrength")
                        .HasColumnType("integer")
                        .HasColumnName("max_reps_strength");

                    b.Property<int>("MinRepsEndurance")
                        .HasColumnType("integer")
                        .HasColumnName("min_reps_endurance");

                    b.Property<int>("MinRepsHypertrophy")
                        .HasColumnType("integer")
                        .HasColumnName("min_reps_hypertrophy");

                    b.Property<int>("MinRepsStrength")
                        .HasColumnType("integer")
                        .HasColumnName("min_reps_strength");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_ar");

                    b.Property<string>("NameDarija")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_darija");

                    b.Property<string>("NameEn")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_en");

                    b.Property<string>("NameFr")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_fr");

                    b.Property<string>("PrimaryMuscle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_muscle");

                    b.Property<string>("RecommendedTempo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recommended_tempo");

                    b.Property<int>("RequiredEquipment")
                        .HasColumnType("integer")
                        .HasColumnName("required_equipment");

                    b.Property<List<string>>("RiskFactors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("risk_factors");

                    b.Property<List<string>>("SearchTags")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("search_tags");

                    b.Property<List<MuscleGroup>>("SecondaryMuscles")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("secondary_muscles");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thumbnail_url");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("VideoDemoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_demo_url");

                    b.Property<string>("VideoFormUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_form_url");

                    b.Property<string>("VideoMistakesUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_mistakes_url");

                    b.Property<string>("VideoTipsUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("video_tips_url");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Difficulty");

                    b.HasIndex("IsActive");

                    b.HasIndex("PrimaryMuscle");

                    b.ToTable("exercises", (string)null);
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Live", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChaptersJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GeneratedSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeakViewers")
                        .HasColumnType("integer");

                    b.Property<string>("ReplayUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StreamUrl")
                        .HasColumnType("text");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalComments")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLikes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalViews")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Lives");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiAnalysisText")
                        .HasColumnType("text");

                    b.Property<decimal>("CarbsG")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FatsG")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FiberG")
                        .HasColumnType("numeric");

                    b.Property<string>("ItemsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MealType")
                        .HasColumnType("integer");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<decimal>("ProteinsG")
                        .HasColumnType("numeric");

                    b.Property<int>("TotalCalories")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasScanned")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.NutritionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AiGenerated")
                        .HasColumnType("boolean");

                    b.Property<string>("AiPromptUsed")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("integer");

                    b.Property<decimal>("TargetCarbsG")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TargetFatsG")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TargetProteinsG")
                        .HasColumnType("numeric");

                    b.Property<int>("TdeeKcal")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("WeekStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<decimal>("CommissionPercent")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("DiscountedPriceMad")
                        .HasColumnType("numeric");

                    b.Property<List<string>>("ImageUrls")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PriceMad")
                        .HasColumnType("numeric");

                    b.Property<string>("SpecsJson")
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("SupplierId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.ProgressPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiAnalysisJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EstimatedBodyFatPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsSharedCommunity")
                        .HasColumnType("boolean");

                    b.Property<string>("PoseType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StorageUrlEncrypted")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TakenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProgressPhotos");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Recipe", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CaloriesPerServing")
                        .HasColumnType("integer");

                    b.Property<decimal>("CarbsGPerServing")
                        .HasColumnType("numeric");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<int>("CookTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FatsGPerServing")
                        .HasColumnType("numeric");

                    b.Property<string>("IngredientsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBulking")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCutting")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGlutenFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRamadanFriendly")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVegan")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVegetarian")
                        .HasColumnType("boolean");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<int>("PrepTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("ProteinsGPerServing")
                        .HasColumnType("numeric");

                    b.Property<int>("Servings")
                        .HasColumnType("integer");

                    b.Property<string>("StepsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("TitleAr")
                        .HasColumnType("text");

                    b.Property<string>("TitleFr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("actual_duration_minutes");

                    b.Property<string>("AiPromptContext")
                        .HasColumnType("text")
                        .HasColumnName("ai_prompt_context");

                    b.Property<string>("AiResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_response_json");

                    b.Property<string>("AiSummary")
                        .HasColumnType("text")
                        .HasColumnName("ai_summary");

                    b.Property<decimal?>("AverageIntensityPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("average_intensity_percent");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime>("GeneratedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<List<string>>("PersonalRecords")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("personal_records");

                    b.Property<int>("PlannedDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("planned_duration_minutes");

                    b.Property<string>("PrimaryMuscleGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_muscle_group");

                    b.Property<List<string>>("Recommendations")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommendations");

                    b.Property<int?>("RecoveryScore")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_score");

                    b.Property<List<MuscleGroup>>("SecondaryMuscleGroups")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("secondary_muscle_groups");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int?>("TotalReps")
                        .HasColumnType("integer")
                        .HasColumnName("total_reps");

                    b.Property<int?>("TotalSets")
                        .HasColumnType("integer")
                        .HasColumnName("total_sets");

                    b.Property<decimal?>("TotalVolumeKg")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("total_volume_kg");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("UserFatigueRating")
                        .HasColumnType("integer")
                        .HasColumnName("user_fatigue_rating");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("BigBoss.Core.Entities.SessionExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ai_notes");

                    b.Property<decimal?>("AverageFormScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("average_form_score");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid")
                        .HasColumnName("exercise_id");

                    b.Property<List<int>>("FormScores")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("form_scores");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsSkipped")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_skipped");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<List<int>>("RepsCompleted")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("reps_completed");

                    b.Property<int>("RepsPlanned")
                        .HasColumnType("integer")
                        .HasColumnName("reps_planned");

                    b.Property<List<int>>("RestSecondsActual")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("rest_seconds_actual");

                    b.Property<int>("RestSecondsPlanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(90)
                        .HasColumnName("rest_seconds_planned");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<int>("SetsCompleted")
                        .HasColumnType("integer")
                        .HasColumnName("sets_completed");

                    b.Property<int>("SetsPlanned")
                        .HasColumnType("integer")
                        .HasColumnName("sets_planned");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("skip_reason");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("UserNotes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_notes");

                    b.Property<decimal?>("WeightPlannedKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("weight_planned_kg");

                    b.Property<List<decimal>>("WeightsCompletedKg")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("weights_completed_kg");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionId");

                    b.ToTable("session_exercises", (string)null);
                });

            modelBuilder.Entity("BigBoss.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AvailableEquipment")
                        .HasColumnType("integer")
                        .HasColumnName("available_equipment");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("goal");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height_cm");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<bool>("NotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("notifications_enabled");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("fr")
                        .HasColumnName("preferred_language");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscription_expires_at");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_tier");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("SubscriptionTier");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BigBoss.Core.Entities.BodyStat", b =>
                {
                    b.HasOne("BigBoss.Core.Entities.User", "User")
                        .WithMany("BodyStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.CoachMessage", b =>
                {
                    b.HasOne("BigBoss.Core.Entities.User", "User")
                        .WithMany("CoachMessages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Meal", b =>
                {
                    b.HasOne("BigBoss.Core.Entities.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.NutritionPlan", b =>
                {
                    b.HasOne("BigBoss.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.ProgressPhoto", b =>
                {
                    b.HasOne("BigBoss.Core.Entities.User", "User")
                        .WithMany("ProgressPhotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Session", b =>
                {
                    b.HasOne("BigBoss.Core.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.SessionExercise", b =>
                {
                    b.HasOne("BigBoss.Core.Entities.Exercise", "Exercise")
                        .WithMany("SessionExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BigBoss.Core.Entities.Session", "Session")
                        .WithMany("SessionExercises")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Exercise", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.Session", b =>
                {
                    b.Navigation("SessionExercises");
                });

            modelBuilder.Entity("BigBoss.Core.Entities.User", b =>
                {
                    b.Navigation("BodyStats");

                    b.Navigation("CoachMessages");

                    b.Navigation("Meals");

                    b.Navigation("ProgressPhotos");

                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
